import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { getPhpFiles, writeFileEnsureDir } from '../utils/file.js';
import { parseEnumFile, type EnumDefinition } from '../utils/php-parser.js';

export type EnumGeneratorOptions = {
  enumsDir: string;
  outputDir: string;
  packageName: string;
};

/**
 * Generate TypeScript type declarations for enums.
 */
export function generateEnumTypeScript(enums: Record<string, EnumDefinition>): string {
  const lines: string[] = [];
  lines.push('// This file is auto-generated by the primcloud Vite plugin.');
  lines.push('// Do not edit directly.');
  lines.push('');

  for (const enumName of Object.keys(enums)) {
    const enumDef = enums[enumName];
    const hasLabels = enumDef.cases.some((c) => c.label);

    if (hasLabels) {
      // Generate a const object with typed properties for enums with labels
      lines.push(`export declare const ${enumDef.name}: {`);
      for (const c of enumDef.cases) {
        const val = String(c.value).replace(/'/g, "\\'");
        const label = c.label ? String(c.label).replace(/'/g, "\\'") : val;
        lines.push(`    ${c.key}: { value: '${val}'; label: '${label}' };`);
      }
      lines.push('};');
      lines.push('');
    } else {
      // Generate a traditional enum for enums without labels
      lines.push(`export enum ${enumDef.name} {`);
      for (const c of enumDef.cases) {
        const val = c.value;
        if (enumDef.backing === 'int' || enumDef.backing === 'integer') {
          if (!isNaN(Number(val))) {
            lines.push(`    ${c.key} = ${val},`);
          } else {
            lines.push(`    ${c.key} = '${val}',`);
          }
        } else {
          lines.push(`    ${c.key} = '${String(val).replace(/'/g, "\\'")}',`);
        }
      }
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Generate runtime JavaScript for enums.
 */
export function generateEnumRuntime(enums: Record<string, EnumDefinition>): string {
  const lines: string[] = [];
  lines.push('// Auto-generated by primcloud Vite plugin');
  lines.push('');

  for (const enumName of Object.keys(enums)) {
    const enumDef = enums[enumName];
    const hasLabels = enumDef.cases.some((c) => c.label);

    lines.push(`export const ${enumDef.name} = {`);
    for (const c of enumDef.cases) {
      const val = String(c.value).replace(/'/g, "\\'");
      if (hasLabels) {
        const label = c.label ? String(c.label).replace(/'/g, "\\'") : val;
        lines.push(`  ${c.key}: { value: '${val}', label: '${label}' },`);
      } else {
        lines.push(`  ${c.key}: '${val}',`);
      }
    }
    lines.push('};');
    lines.push('');
  }

  lines.push('export default {};');
  return lines.join('\n');
}

/**
 * Collect all enum definitions from the enums directory.
 */
export function collectEnums(enumsDir: string): Record<string, EnumDefinition> {
  const enums: Record<string, EnumDefinition> = {};

  if (!existsSync(enumsDir)) {
    return enums;
  }

  const enumFiles = getPhpFiles(enumsDir);

  for (const file of enumFiles) {
    try {
      const enumPath = join(enumsDir, file);
      const def = parseEnumFile(enumPath);
      if (def) {
        enums[def.name] = def;
      }
    } catch (e) {
      // Ignore parse errors
      console.warn(`Failed to parse enum file: ${file}`, e);
    }
  }

  return enums;
}

/**
 * Generate enum files (TypeScript declarations and runtime JavaScript).
 */
export function generateEnums(options: EnumGeneratorOptions): void {
  const { enumsDir, outputDir, packageName } = options;

  // Collect all enums
  const enums = collectEnums(enumsDir);

  // Generate TypeScript declarations
  const dtsContent = generateEnumTypeScript(enums);
  const dtsPath = join(outputDir, 'index.d.ts');
  writeFileEnsureDir(dtsPath, dtsContent);

  // Generate runtime JavaScript
  const jsContent = generateEnumRuntime(enums);
  const jsPath = join(outputDir, 'index.js');
  writeFileEnsureDir(jsPath, jsContent);

  // Generate package.json
  const pkgJson = JSON.stringify(
    {
      name: packageName,
      version: '0.0.0',
      main: 'index.js',
      types: 'index.d.ts',
    },
    null,
    2
  );
  const pkgPath = join(outputDir, 'package.json');
  writeFileEnsureDir(pkgPath, pkgJson);
}
