import { join } from 'node:path';
import { writeFileEnsureDir } from '../utils/file.js';
import type { ModuleFile } from './registry.js';

const HEADER = `// Generated by vite-plugin-ferry. Do not edit.
// This file is regenerated on every Vite run.`;

export type AmbientTypesInput = {
  /** Script-style declaration blocks (declare module / declare function / interface). */
  blocks: string[];
  /** Separate module-style files, pulled in by a triple-slash reference from index.d.ts. */
  moduleFiles?: ModuleFile[];
};

/**
 * Assemble the script-style ambient `index.d.ts`.
 *
 * The output MUST be a script, not a module: zero top-level `import`/`export`, so
 * the bare-specifier `declare module '@ferry/...'` blocks stay globally visible.
 * Module-style augmentations (which need imports) live in separate files, referenced
 * here by triple-slash directives — those must precede all other content.
 */
export function assembleAmbientTypes(input: AmbientTypesInput): string {
  const { blocks, moduleFiles = [] } = input;

  const parts: string[] = [];

  // Triple-slash references first: only comments and other directives may precede them.
  for (const file of moduleFiles) {
    parts.push(`/// <reference path="./${file.fileName}" />`);
  }

  parts.push(HEADER);

  for (const block of blocks) {
    parts.push(block.trim());
  }

  return parts.join('\n\n') + '\n';
}

/**
 * Write the ambient declarations into `typesDir`: the script-style `index.d.ts`,
 * each separate module file, and a minimal `package.json`. Regenerated on every run.
 */
export function writeAmbientTypes(typesDir: string, input: AmbientTypesInput): void {
  writeFileEnsureDir(join(typesDir, 'index.d.ts'), assembleAmbientTypes(input));

  for (const file of input.moduleFiles ?? []) {
    writeFileEnsureDir(join(typesDir, file.fileName), file.content.trim() + '\n');
  }

  const pkgJson = JSON.stringify(
    {
      name: '@types/vite-plugin-ferry',
      version: '0.0.0',
      types: 'index.d.ts',
    },
    null,
    2
  );
  writeFileEnsureDir(join(typesDir, 'package.json'), pkgJson + '\n');
}
